### ISSUE TITLE
401 error - login function of userService not called

### ISSUE THREAD

**Issue by perpendicularpiped** [sweetvanloan/Thoughtify#7]
### Description of issue
It appears that our userService.js has a login function that is not participating in the login workflow. Trying to log in results in a HTTP 401 error. Also signing up does enter a user into Atlas but still throws an error anyways
### Error messages or screenshots
POST /api/users/login 401 30.414 ms - 25
### Steps attempted to resolve the issue
We tried to console log within the try statement of the login function to no avail. No logs to console.
### Research
https://medium.com/to-err-is-aaron/detect-network-failures-when-using-fetch-40a53d56e36
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

**Comment by myDeveloperJourney** [comment]
@forkitupforkitup @sweetvanloan @KoalaCodes Here's a summary of steps taken to resolve issue - _(please close this ticket once you've read this comment)_ 😄 

1. There was a mismatch between `req.body` and the individual properties on the user document we were trying to find the user document by and compare the password with.

1. The `comparePassword` schema method was incomplete and wasn't invoking the callback function with the appropriate data for the controller.

1. Once the corrections were made it was apparent we were trying to login with the wrong user credentials.

1. The last issue we discovered was that we weren't appropriately passing the props object from the route component to the `loginPage` component.
